version: '3'
services:
  metro:
    image: pavan17761a0253/phonepaymetro:v1
    ports:
      - "8001:80"
    deploy:
      replicas: 3

  train:
    image: pavan17761a0253/phonepaytrain:v1
    ports:
      - "8002:80"
    deploy:
      replicas: 3
      
  bus:
    image: pavan17761a0253/phonepaybus:v1
    ports:
      - "8003:80"
    deploy:
      replicas: 3
